#!/usr/bin/env python3
"""Generate lib/microreader/display/BlinkImages.h from resources/blink/Blink{1,2}.bmp.

The two BMPs (528x792, 2bpp) share one canvas, so the eyelid keeps its place
between the frames. Both are cropped to the union of their dark pixels and
thresholded to 1bpp (MSB first, 1 = white) -- the layout DrawBuffer::blit_1bit_row()
takes. Re-run after editing the BMPs:  python tools/generate_blink.py
"""
import os
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path):
    d = open(path, "rb").read()
    off, = struct.unpack_from("<I", d, 10)
    w, h, _, bpp = struct.unpack_from("<iiHH", d, 18)
    assert bpp == 2, "expected a 2bpp BMP"
    top_down = h < 0
    h = abs(h)
    stride = ((w * 2 + 31) // 32) * 4
    black = [[False] * w for _ in range(h)]  # palette index 0/1 = dark
    for y in range(h):
        src_y = y if top_down else h - 1 - y
        row = d[off + src_y * stride: off + (src_y + 1) * stride]
        for x in range(w):
            black[y][x] = ((row[x // 4] >> (6 - (x % 4) * 2)) & 3) < 2
    return w, h, black


imgs = [load(os.path.join(ROOT, "resources/blink", f"Blink{i}.bmp")) for i in (1, 2)]
w, h = imgs[0][:2]
assert all(i[:2] == (w, h) for i in imgs)

x0, y0, x1, y1 = w, h, 0, 0
for _, _, px in imgs:
    for y in range(h):
        for x in range(w):
            if px[y][x]:
                x0, y0, x1, y1 = min(x0, x), min(y0, y), max(x1, x + 1), max(y1, y + 1)
x0 -= x0 % 8  # byte-align the left edge too
cw, ch = (x1 - x0 + 7) // 8 * 8, y1 - y0
stride = cw // 8

out = ["// Generated by tools/generate_blink.py from resources/blink/Blink{1,2}.bmp -- do not edit.",
       "// 1bpp, MSB first, 1 = white; both frames share one crop so the eyelid keeps its place.",
       "#pragma once", "", "#include <cstdint>", "", "namespace microreader {", "",
       f"inline constexpr int kBlinkWidth = {cw};", f"inline constexpr int kBlinkHeight = {ch};", ""]
for n, (_, _, px) in enumerate(imgs, 1):
    data = bytearray()
    for y in range(y0, y1):
        for bx in range(stride):
            b = 0
            for k in range(8):
                x = x0 + bx * 8 + k
                dark = x < w and px[y][x]
                b = (b << 1) | (0 if dark else 1)
            data.append(b)
    out.append(f"inline constexpr uint8_t kBlink{n}[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        out.append("    " + ",".join(f"0x{v:02X}" for v in data[i:i + 24]) + ",")
    out += ["};", ""]
out.append("}  // namespace microreader")
open(os.path.join(ROOT, "lib/microreader/display/BlinkImages.h"), "w").write("\n".join(out) + "\n")
print("crop", cw, "x", ch)
