import os
import subprocess

# The version comes from git only:
#   base version = the latest reachable "v<N>..." tag, without the leading "v"
#   build number = total commit count of HEAD
#   dirty        = uncommitted changes in the working tree at build time
# A release is therefore made by tagging (git tag v2.2.2); there is no version file.


def git(root_dir, *args):
    return subprocess.check_output(
        ['git', *args], cwd=root_dir, stderr=subprocess.DEVNULL
    ).strip().decode('utf-8')


def get_git_info(root_dir):
    try:
        base = git(root_dir, 'describe', '--tags', '--abbrev=0', '--match', 'v[0-9]*').lstrip('v')
    except Exception:
        base = "0.0.0"  # no v* tag reachable (e.g. shallow clone without tags)
    try:
        count = git(root_dir, 'rev-list', '--count', 'HEAD')
        hash_str = git(root_dir, 'rev-parse', '--short', 'HEAD')
        dirty = bool(git(root_dir, 'status', '--porcelain'))
    except Exception:
        count, hash_str, dirty = "0", "unknown", False
    return base, count, hash_str, dirty


def generate():
    try:
        Import("env") # SCons / PlatformIO hook
        root_dir = env.get("PROJECT_DIR")
    except NameError:
        root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    header_file = os.path.join(root_dir, 'lib', 'microreader', 'version.h')

    base_version, build_count, git_hash, dirty = get_git_info(root_dir)
    full_version = f"{base_version}.{build_count}"

    header_content = f"""// Auto-generated by tools/generate_version.py
#pragma once

#define MICROREADER_VERSION "{full_version}"
#define MICROREADER_DIRTY {1 if dirty else 0}
#define MICROREADER_GIT_HASH "{git_hash}"
"""

    # Write only if changed to avoid unnecessary recompilations
    current_content = ""
    if os.path.exists(header_file):
        with open(header_file, 'r', encoding='utf-8') as f:
            current_content = f.read()

    if current_content != header_content:
        with open(header_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"Generated version.h: {full_version}{' (dirty)' if dirty else ''}")

generate()
